### ISSUE TITLE
Script utils

### ISSUE THREAD

**Issue by pwndev** [TBZedu/m122_praxisarbeit#2]
I have create [/bin/bucb.utils](https://github.com/TBZedu/m122_praxisarbeit/blob/main/praxisarbeit/bin/bucb.utils). Here we can add shared functions which will be shared among both scripts: e.g. logging function

**Comment by GeneTv** [comment]
@cvanloo

**Comment by GeneTv** [comment]
I copied the log function to the utils file, you may adjust it in your script.

not a breaking change

**Comment by cvanloo** [comment]
Thanks, I've updated my script.

Closed with effe9be.
