### ISSUE TITLE
Finalize

### ISSUE THREAD

**Issue by GeneTv** [TBZedu/m122_praxisarbeit#3]
We must not forget to finalize everything, create a release and send a mail with the link to DOA before 23:59.

I'm gonna test my script later during the day, for the final functionality assurance. Can only work on my phone til Sat. tho, since I'm not at home. So changes may take bit longer.

@cvanloo

**Comment by cvanloo** [comment]
I finished my testings.

Note the two issues I created regarding `buc` (#4 and #5).

**Comment by GeneTv** [comment]
Done and tested the man, release created. I'm gonna send him the mail
