### ISSUE TITLE
man buc.1: Invalid markup

### ISSUE THREAD

**Issue by cvanloo** [TBZedu/m122_praxisarbeit#5]
The buc.1 man-page is not displayed correctly.

**Actual:**
![image](https://user-images.githubusercontent.com/58854985/175350295-e51b4683-20d5-4320-b548-858e67e74ced.png)

**Expected:**
![image](https://user-images.githubusercontent.com/58854985/175350158-9a0b9e7e-308f-4d08-9bd1-f716105046f6.png)

@GeneTv What command did you use to generate the file?

I used `pandoc buc.1.md -s -t man -o buc.1`

**Comment by GeneTv** [comment]
I usee the same command and it was displayed correctly for me

**Comment by cvanloo** [comment]
Can you try my version? I guess it's better to use something that works for both.

Although it's weird that the same command generates different markup.
